- controller/app/cmdline/src/cmd_line.cpp
- controller/lib/include/stream_input_descriptor.h
- controller/lib/include/stream_output_descriptor.h
- controller/lib/src/audio_unit_descriptor_imp.cpp
- controller/lib/src/audio_unit_descriptor_imp.h
- controller/lib/src/audio_unit_get_sampling_rate_response_imp.cpp
- controller/lib/src/clock_domain_descriptor_imp.cpp
- controller/lib/src/clock_domain_descriptor_imp.h
- controller/lib/src/stream_input_descriptor_imp.cpp
- controller/lib/src/stream_input_descriptor_imp.h
- controller/lib/src/stream_output_descriptor_imp.cpp
- controller/lib/src/stream_output_descriptor_imp.h
Now each set command response updates the corresponding descriptor frame with the new set value.  The UI returns this updated value from the descriptor response class.  Set stream_format, set sampling_rate were unable to be tested.
> Revise currently implemented SET_ commands

- controller/lib/src/audio_cluster_descriptor_imp.cpp
- controller/lib/src/audio_map_descriptor_imp.cpp
Audio_map and audio_cluster were not reading the response frame from the descriptor buffer.
> audio_map and audio_cluster

- controller/app/cmdline/src/cmd_line.cpp
The out_descriptor info in function cmd_disconnect_rx was optained from the in stream end station where it should be the outstream endstation.
> cmd_disconnect_rx wrong out_descriptor

- controller/lib/src/stream_port_input_descriptor_imp.cpp
- controller/lib/src/stream_port_output_descriptor_imp.cpp
Now we can queue pending maps past the number of maps allowed for one command.
> Store Pending Audio Maps revision

- controller/lib/src/avb_interface_descriptor_imp.cpp
This assert is removed because we don't want an application to halt due
to one bad AVDECC entity on the network.
> controller: lib: src: avb_inteface, remove assert if get_counters fails

- controller/lib/src/msvc/net_interface_imp.cpp
Packet filter count should be 1, not 0.
> avdecc - msvc net interface - fix bug in ethernet filter setting

- controller/app/cmdline/src/cmd_line.cpp
- controller/lib/include/stream_input_get_rx_state_response.h
- controller/lib/src/stream_input_get_rx_state_response_imp.cpp
- controller/lib/src/stream_input_get_rx_state_response_imp.h
add methods to read talker entity id and listener entity id fields
> get_rx_state_response additions

- controller/app/cmdline/src/cmd_line_main.cpp
GNU's Readline and OSX's default Libedit libraries have different types for 'rl_completion_entry_function'.
> cmd_line_main - support both libedit and GNU Readline libraries

- controller/lib/src/audio_unit_descriptor_imp.cpp
- controller/lib/src/clock_domain_descriptor_imp.cpp
- controller/lib/src/descriptor_base_imp.cpp
- controller/lib/src/stream_input_descriptor_imp.cpp
- controller/lib/src/stream_output_descriptor_imp.cpp
It is unnecessary to update a descriptor with a failed SET command's response.
> SET_ response error check

- controller/lib/src/acmp_controller_state_machine.cpp
match aecp log message parameter order (sequence id and command status were flipped)
> post_log_msg() parameter order consistency

- controller/app/cmdline/src/cmd_line.cpp
- controller/lib/include/net_interface.h
- controller/lib/src/linux/net_interface_imp.cpp
- controller/lib/src/linux/net_interface_imp.h
- controller/lib/src/msvc/net_interface_imp.cpp
- controller/lib/src/msvc/net_interface_imp.h
- controller/lib/src/osx/net_interface_imp.cpp
- controller/lib/src/osx/net_interface_imp.h
Add API's to fetch the ipv4 address(es) associated with a network interface.
Linux implementation needed.
> network interface IP address

- controller/lib/src/msvc/net_interface_imp.cpp
use inet_pton() instead of the deprecated inet_addr()
> net_interface - msvc - fix warning

- controller/app/cmdline/src/cmd_line.h
- controller/app/cmdline/src/cmd_line_main.cpp
> cmdline - explicitly flush stdout after a printf

- controller/lib/src/msvc/net_interface_imp.cpp
- controller/lib/src/version.h
Using GetAdaptersInfo() rather than SendARP() to get the MAC address of each network interface.
> msvc - net interface - network interface mac address fix

- controller/app/cmdline/src/cmd_line_main.cpp
Added command line argument to print a new line with an underscore in between commands (useful for a script reading avdecccmdline stdout via readline())
> cmdline - msvc - add optional cmdline argument

- controller/lib/src/aecp_controller_state_machine.cpp
- controller/lib/src/end_station_imp.cpp
- controller/lib/src/inflight.h
- controller/lib/src/linux/system_layer2_multithreaded_callback.cpp
Fix for the XMOS firmware upgrade issue as reported in Issue #303: AECP in-progress responses in firmware upgrade should be polled rather than checked once.
> Fix for XMOS firmware upgrade issue

- README.md
- controller/app/cmdline/CMakeLists.txt
- controller/app/cmdline/src/cmd_line_main.cpp
add optional cmake command line argument to use GNU Readline rather than default libedit
> cmdline - #287 - readline library fix

- controller/app/cmdline/src/cmd_line.cpp
- controller/lib/include/util.h
- controller/lib/src/util.cpp
- Add utility API
```c++
///
/// Encode a string with Quoted-Printable encoding.
///
AVDECC_CONTROLLER_LIB32_API const char * qprintable_encode(const char * input_cstr);
```
- Encode avdecccmdline cmd_list() strings
> Quoted-Printable string encoding

- controller/lib/include/response_frame.h
- controller/lib/src/audio_unit_descriptor_imp.cpp
- controller/lib/src/avb_interface_descriptor_imp.cpp
- controller/lib/src/clock_domain_descriptor_imp.cpp
- controller/lib/src/descriptor_base_imp.cpp
- controller/lib/src/descriptor_base_imp.h
- controller/lib/src/entity_descriptor_imp.cpp
- controller/lib/src/response_frame.cpp
- controller/lib/src/stream_input_descriptor_imp.cpp
- controller/lib/src/stream_output_descriptor_imp.cpp
- controller/lib/src/stream_port_input_descriptor_imp.cpp
- controller/lib/src/stream_port_output_descriptor_imp.cpp
Store get_ command response buffers in a map by command type so client code can asynchronously send and process multiple commands per descriptor.
> store 1722.1 get_ cmd response buffers in a map

- controller/app/cmdline/src/cmd_line.cpp
- controller/lib/include/stream_output_descriptor.h
- controller/lib/src/stream_output_descriptor_imp.cpp
- controller/lib/src/stream_output_descriptor_imp.h
1. Connection_count was hardcoded to 0 
2. Listener GUID and Listener stream index were provided as arguments
(They are always '00:00:00:00:00:00:00:00' and '0' for a get_tx_connection commands)
> Fix get_tx_connection API

- controller/lib/src/end_station_imp.cpp
Fixes the scenario where an unsolicited ACMP response is processed before the Entity Descriptor is stored.
> end station - ACMP - check entity_desc_vec size to avoid std::vector out_of_range exception

- controller/app/cmdline/src/cmd_line.cpp
- controller/app/cmdline/src/cmd_line.h
Just ran into this today. Hoping it would help make things more clear for new users (like myself).
> Fix cmdline help text for "help disconnect rx"

- controller/lib/src/controller_imp.cpp
AEM commands that return NOT_IMPLEMENTED should return a copy of the command pdu with the command set to response and the error code updated. The length should be that of the command.
Since unimplemented responses may not be the size expected for jdksavdecc_aem_command_...read() to succeed, we need to read the status from the frame directly.
> AEM unimplemented responses

- .gitmodules
Forking into a non-Github environment breaks the old submodule
configuration. Use an absolute URL to make forkers happy. :smile:
> Absolute submodule URL.
