audioscience/avdecc-lib

controller/app/cmdline/src/cmd_line.cpp, controller/app/cmdline/src/cmd_line.h
object_name and localized_descriptor read from response class where applicable.
=> fix view_all

.travis.yml, README.md, controller/app/cmdline/src/cmd_line.cpp, controller/lib/src/audio_map_descriptor_response_imp.cpp, controller/lib/src/audio_unit_descriptor_response_imp.cpp, controller/lib/src/clock_domain_descriptor_response_imp.cpp, controller/lib/src/util.cpp, travis.sh
=> Linux build fix

controller/app/cmdline/src/cmd_line.cpp
show localized description where name is not yet set, fix formatting
=> connect cmd fixes

controller/app/cmdline/src/cmd_line.cpp, controller/app/cmdline/src/cmd_line.h, controller/lib/include/controller.h, controller/lib/include/stream_port_input_descriptor.h, controller/lib/include/stream_port_input_get_audio_map_response.h, controller/lib/include/stream_port_output_descriptor.h, controller/lib/include/stream_port_output_get_audio_map_response.h, controller/lib/src/aecp_controller_state_machine.cpp, controller/lib/src/aecp_controller_state_machine.h, controller/lib/src/clock_domain_descriptor_imp.cpp, controller/lib/src/end_station_imp.cpp, controller/lib/src/stream_port_input_descriptor_imp.cpp, controller/lib/src/stream_port_input_descriptor_imp.h, controller/lib/src/stream_port_input_get_audio_map_response_imp.cpp, controller/lib/src/stream_port_input_get_audio_map_response_imp.h, controller/lib/src/stream_port_output_descriptor_imp.cpp, controller/lib/src/stream_port_output_descriptor_imp.h, controller/lib/src/stream_port_output_get_audio_map_response_imp.cpp, controller/lib/src/stream_port_output_get_audio_map_response_imp.h
Adding GET, ADD, and REMOVE audio mappings commands.  Also adding internal commands ADD_PENDING, VIEW_PENDING, and CLEAR_PENDING to queue audio mappings in the library for adding or removal.
=> Audio mappings

controller/lib/src/stream_port_input_descriptor_imp.cpp, controller/lib/src/stream_port_output_descriptor_imp.cpp
clear library queued audio mappings after every command response (success or failure)
=> clear pending audio mappings

controller/lib/src/controller_imp.cpp
The issue was in the freeing/reallocation of the state machines.
=> Shutdown restart fix

controller/lib/src/msvc/system_layer2_multithreaded_callback.cpp, controller/lib/src/msvc/system_message_queue.cpp, controller/lib/src/msvc/system_message_queue.h
fix descriptor enumeration bug - convert message queues to growable STL lists
=> msg queue bugfix

controller/lib/include/util.h, controller/lib/src/util.cpp
add API to convert stream format name to stream format description
=> avdecc - util - format name to description 

controller/app/cmdline/src/cmd_line.cpp, controller/lib/include/stream_input_descriptor_response.h, controller/lib/include/stream_output_descriptor_response.h, controller/lib/src/stream_input_descriptor_response_imp.cpp, controller/lib/src/stream_input_descriptor_response_imp.h, controller/lib/src/stream_output_descriptor_response_imp.cpp, controller/lib/src/stream_output_descriptor_response_imp.h
Store supported stream formats and add API to fetch them.
=> avdecc - stream_input/stream_output supported formats

controller/app/cmdline/src/cmd_line.cpp
new notification id needed for each get_rx_state()/get_tx_state() command
=> cmdline - cmd_show_connections bug fix

controller/lib/src/acmp_controller_state_machine.cpp
Include descriptor index for get_rx_state() notification callback
=> avdecc - acmp

controller/lib/include/end_station.h, controller/lib/src/end_station_imp.cpp, controller/lib/src/end_station_imp.h
=> end_station - include advertised gptp_grandmaster_id field

controller/lib/src/version.h
=> avdecc-lib v0.6.2

controller/lib/CMakeLists.txt
=> cmake - add name to osx build

controller/lib/include/descriptor_base.h, controller/lib/src/descriptor_base_imp.cpp, controller/lib/src/descriptor_base_imp.h
=> Add API to read owning guid returned from an unsolicited lock/acquire

controller/app/cmdline/src/cmd_line.cpp, controller/app/cmdline/src/cmd_line.h
add a command to fetch the connection status of an end station by list index or GUID
=> cmdline - get connection_status

controller/app/cmdline/src/cmd_line.cpp, controller/lib/include/stream_output_descriptor.h, controller/lib/src/stream_output_descriptor_imp.cpp, controller/lib/src/stream_output_descriptor_imp.h
=> implement set_stream_info - msrp_accumulated_latency

controller/lib/src/osx/net_interface_imp.cpp
use return code rather than exit(); log callback instead of perror
=> osx - net interface 

controller/app/cmdline/src/cmd_line.cpp, controller/lib/src/end_station_imp.cpp, controller/lib/src/end_station_imp.h, controller/lib/src/entity_descriptor_imp.cpp
Previously, only 1 configuration was stored.
=> Enumerate multiple configurations

controller/lib/include/controller.h, controller/lib/src/adp.cpp, controller/lib/src/adp.h, controller/lib/src/controller_imp.cpp, controller/lib/src/controller_imp.h, controller/lib/src/linux/net_interface_imp.cpp, controller/lib/src/linux/net_interface_imp.h, controller/lib/src/msvc/net_interface_imp.cpp, controller/lib/src/msvc/net_interface_imp.h, controller/lib/src/osx/net_interface_imp.cpp, controller/lib/src/osx/net_interface_imp.h
Store the selected network interface EUI (controller GUID) and add a controller API to change it.
=> Controller Entity ID

controller/app/cmdline/src/cmd_line.cpp, controller/app/cmdline/src/cmd_line.h, controller/lib/include/stream_output_descriptor.h, controller/lib/src/acmp_controller_state_machine.cpp, controller/lib/src/controller_imp.cpp, controller/lib/src/end_station_imp.cpp, controller/lib/src/stream_output_descriptor_imp.cpp, controller/lib/src/stream_output_descriptor_imp.h
- Add 1722.1 disconnect_tx API
- Split up avdecccmdline disconnect into rx and tx
=> 1722.1 disconnect_tx API

controller/lib/src/end_station_imp.cpp
aem/acmp - check for valid entity_desc_vec and config_desc_vec size
=> more end_station aem/acmp std::vector out_of_range checks

controller/app/cmdline/src/cmd_line.cpp, controller/app/cmdline/src/cmd_line.h, controller/lib/include/util.h, controller/lib/src/util.cpp
- Move and simplify qprintable_encode() to fix #344 
- Widen the cmd_list columns
- MSVC warning fixes
=> Quoted Printable bug fix

controller/lib/include/util.h, controller/lib/src/util.cpp
- value -> subtype
- value -> sample rate
- value -> channel count
=> util - add 1722 format conversion APIs
